version: "3.7"
# docker-compose for development processes

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
    command: [ "make", "local_run" ]
    environment:
      POSTGRES_PASSWORD: health
      POSTGRES_USER: health
      POSTGRES_DB: health
    volumes:
      - .:/usr/src/app/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - service-network

  postgres:
    image: postgres:14
    ports:
      - "54328:5432"
    environment:
      POSTGRES_PASSWORD: health
      POSTGRES_USER: health
      POSTGRES_DB: health
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U health -d health" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - service-network

  liquibase:
    image: liquibase/liquibase
    command: --defaults-file=/liquibase/changelog/liquibase.properties --searchPath=/liquibase/changelog/ update
    volumes:
      - ./migrations/:/liquibase/changelog/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
